"use client";

import { useState } from "react";
import {
  ActionIcon,
  Alert,
  Badge,
  Button,
  Group,
  Stack,
  Table,
  Text,
  TextInput,
  Title,
} from "@mantine/core";
import { warningsForField, type ArithmeticWarning } from "@/lib/arithmetic";
import { addressKey, type EditedFields, type FieldAddress } from "@/lib/field-edit";
import {
  fieldRows,
  isVisitorTyped,
  itemNeedsReview,
  itemVisitorTyped,
  lineItemRows,
  needsReview,
  readNoLineItems,
  type FieldRow,
  type LineItemRow,
} from "@/lib/receipt-fields";
import type { Receipt } from "@/lib/receipt-schema";
import classes from "./FieldPanel.module.css";

/**
 * Commits one edit and says whether the app took it.
 *
 * The answer comes back in the same pass, so a cell that was refused can put the
 * previous value back without waiting for a render.
 */
export type CommitEdit = (address: FieldAddress, text: string) => boolean;

/** The refusal sentence against each field that refused one, keyed by address. */
export type Rejections = Record<string, string>;

type PanelProps = {
  receipt: Receipt;
  warnings: ArithmeticWarning[];
  edited: EditedFields;
  rejections: Rejections;
  onCommit: CommitEdit;
  onAddItem: () => void;
  onRemoveItem: (index: number) => void;
  /** One key per line item, generated by the workspace and never exported. */
  itemKeys: string[];
};

/**
 * One editable value.
 *
 * The draft lives here rather than in the workspace, because a draft is not a
 * fact about the receipt and nothing that has passed no validation belongs
 * beside the values that have. Blur and Enter commit, Escape puts back the value
 * the app holds, and nothing in between reaches the receipt, so a half-typed
 * "2026-1" is refused by nobody.
 */
function EditableCell({
  row,
  name,
  rejection,
  onCommit,
  align = "left",
}: {
  row: FieldRow;
  name: string;
  rejection?: string;
  onCommit: CommitEdit;
  align?: "left" | "right";
}) {
  const held = row.value ?? "";
  const [draft, setDraft] = useState(held);
  const [seed, setSeed] = useState(held);

  // The app's value changed under the cell, through a commit, an add or a new
  // extraction, so the draft follows it.
  if (seed !== held) {
    setSeed(held);
    setDraft(held);
  }

  const address = row.address;
  if (!address) {
    return <Value value={row.value} />;
  }

  const commit = () => {
    if (draft === held) {
      return;
    }
    if (!onCommit(address, draft)) {
      // The receipt kept the value it had, so the cell shows that value and the
      // refusal names the text the visitor typed.
      setDraft(held);
    }
  };

  return (
    <TextInput
      aria-label={isVisitorTyped(row) ? `${name}, you typed this` : name}
      value={draft}
      classNames={{ input: isVisitorTyped(row) ? classes.editedInput : classes.cellInput }}
      error={rejection}
      placeholder="absent"
      size="xs"
      variant="filled"
      styles={{ input: { textAlign: align, fontFamily: "var(--mantine-font-family-monospace)" } }}
      onChange={(event) => setDraft(event.currentTarget.value)}
      onBlur={commit}
      onKeyDown={(event) => {
        if (event.key === "Enter") {
          event.preventDefault();
          commit();
        }
        if (event.key === "Escape") {
          event.preventDefault();
          setDraft(held);
        }
      }}
    />
  );
}

/**
 * Prints a value the visitor cannot change, which is the computed row alone.
 *
 * A monetary string keeps its digits and its decimal places, because nothing
 * here reformats, rounds or localizes.
 */
function Value({ value }: { value: string | null }) {
  if (value === null) {
    return (
      <Text component="span" c="dimmed" fs="italic" size="sm">
        absent
      </Text>
    );
  }

  return (
    <Text component="span" ff="monospace" size="sm">
      {value}
    </Text>
  );
}

function Confidence({ row }: { row: FieldRow }) {
  if (isVisitorTyped(row)) {
    return (
      <Badge color="blue" variant="light" size="xs">
        you typed this
      </Badge>
    );
  }

  if (row.confidence === null) {
    return (
      <Text component="span" c="dimmed" size="xs">
        {row.computed ? "computed" : "no confidence given"}
      </Text>
    );
  }

  return (
    <Group gap="xs" wrap="nowrap" justify="flex-end">
      <Text component="span" c="dimmed" size="xs" ff="monospace">
        {row.confidence.toFixed(2)}
      </Text>
      {needsReview(row) ? (
        <Badge color="yellow" variant="light" size="xs">
          check this
        </Badge>
      ) : null}
    </Group>
  );
}

/**
 * The warnings against one row, printed under its value.
 *
 * The wording comes off the warning the arithmetic module composed, so the panel
 * and the JSON download say the same thing about the same gap.
 */
function RowWarnings({ warnings }: { warnings: ArithmeticWarning[] }) {
  if (warnings.length === 0) {
    return null;
  }

  return (
    <Stack gap={2} mt={4}>
      {warnings.map((warning) => (
        <Text key={warning.check} c="yellow.8" size="xs" role="status">
          {warning.message}
        </Text>
      ))}
    </Stack>
  );
}

/** The refusal standing against a row's control, if the app refused one. */
function refusalFor(rejections: Rejections, row: FieldRow): string | undefined {
  return row.address ? rejections[addressKey(row.address)] : undefined;
}

function FlatFields({
  receipt,
  warnings,
  edited,
  rejections,
  onCommit,
}: {
  receipt: Receipt;
  warnings: ArithmeticWarning[];
  edited: EditedFields;
  rejections: Rejections;
  onCommit: CommitEdit;
}) {
  return (
    <Table striped withRowBorders={false} verticalSpacing="xs">
      <Table.Tbody>
        {fieldRows(receipt, edited).map((row, index) => {
          const rowWarnings = row.field ? warningsForField(warnings, row.field) : [];
          const rejection = refusalFor(rejections, row);

          return (
            <Table.Tr key={`${row.label}-${index}`}>
              <Table.Th scope="row" style={{ whiteSpace: "nowrap", fontWeight: 500 }}>
                {row.label}
                {row.computed ? (
                  <Badge color="gray" variant="light" size="xs" ml="xs">
                    computed
                  </Badge>
                ) : null}
              </Table.Th>
              <Table.Td>
                <Stack gap={4}>
                  {row.labelCell ? (
                    <EditableCell
                      row={row.labelCell}
                      name={`${row.label}, label`}
                      rejection={refusalFor(rejections, row.labelCell)}
                      onCommit={onCommit}
                    />
                  ) : null}
                  <EditableCell
                    row={row}
                    name={row.labelCell ? `${row.label}, amount` : row.label}
                    rejection={rejection}
                    onCommit={onCommit}
                  />
                </Stack>
                {row.note ? (
                  <Text c="dimmed" size="xs" mt={2}>
                    {row.note}
                  </Text>
                ) : null}
                <RowWarnings warnings={rowWarnings} />
              </Table.Td>
              <Table.Td style={{ textAlign: "right", verticalAlign: "top" }}>
                <Confidence row={row} />
              </Table.Td>
            </Table.Tr>
          );
        })}
      </Table.Tbody>
    </Table>
  );
}

/** One line item, four controls and the control that removes the row. */
function LineItemRowCells({
  row,
  rejections,
  onCommit,
  onRemoveItem,
}: {
  row: LineItemRow;
  rejections: Rejections;
  onCommit: CommitEdit;
  onRemoveItem: (index: number) => void;
}) {
  const cell = (field: FieldRow, align: "left" | "right") => (
    <EditableCell
      row={field}
      name={`${field.label}, line item ${row.position}`}
      rejection={refusalFor(rejections, field)}
      onCommit={onCommit}
      align={align}
    />
  );

  return (
    <Table.Tr>
      <Table.Td>
        <Group gap="xs" wrap="nowrap" align="flex-start">
          <div style={{ flex: 1, minWidth: 0 }}>{cell(row.description, "left")}</div>
          {itemVisitorTyped(row) ? (
            <Badge color="blue" variant="light" size="xs">
              you typed this
            </Badge>
          ) : null}
          {itemNeedsReview(row) ? (
            <Badge color="yellow" variant="light" size="xs">
              check this
            </Badge>
          ) : null}
        </Group>
      </Table.Td>
      <Table.Td>{cell(row.quantity, "right")}</Table.Td>
      <Table.Td>{cell(row.unitPrice, "right")}</Table.Td>
      <Table.Td>{cell(row.amount, "right")}</Table.Td>
      <Table.Td>
        <ActionIcon
          aria-label={`Remove line item ${row.position}`}
          variant="subtle"
          color="red"
          onClick={() => onRemoveItem(row.index)}
        >
          <Text component="span" aria-hidden size="sm">
            ×
          </Text>
        </ActionIcon>
      </Table.Td>
    </Table.Tr>
  );
}

/**
 * The line items, with the add control under the table.
 *
 * The control sits below the rows so the row it creates appears directly above
 * it, and so tabbing off the last amount reaches the add control rather than
 * passing it on the way in.
 */
function LineItems({
  receipt,
  edited,
  rejections,
  onCommit,
  onAddItem,
  onRemoveItem,
  itemKeys,
}: {
  receipt: Receipt;
  edited: EditedFields;
  rejections: Rejections;
  onCommit: CommitEdit;
  onAddItem: () => void;
  onRemoveItem: (index: number) => void;
  itemKeys: string[];
}) {
  const addControl = (
    <Group>
      <Button variant="subtle" size="xs" onClick={onAddItem}>
        Add a line item
      </Button>
    </Group>
  );

  if (readNoLineItems(receipt)) {
    return (
      <Stack gap="xs">
        <Title order={3} size="h6">
          Line items
        </Title>
        <Text c="dimmed" size="sm">
          The app read no line items off this receipt, so it shows no item total.
          Nothing here says the receipt printed none: a card slip prints a total
          alone, and a long receipt can lose a line to a crease or a fold. Add a
          row if the receipt printed lines the model missed.
        </Text>
        {addControl}
      </Stack>
    );
  }

  return (
    <Stack gap="xs">
      <Title order={3} size="h6">
        Line items
      </Title>
      <Table striped withRowBorders={false} verticalSpacing="xs">
        <Table.Thead>
          <Table.Tr>
            <Table.Th>Description</Table.Th>
            <Table.Th style={{ textAlign: "right" }}>Quantity</Table.Th>
            <Table.Th style={{ textAlign: "right" }}>Unit price</Table.Th>
            <Table.Th style={{ textAlign: "right" }}>Amount</Table.Th>
            <Table.Th>
              <Text component="span" size="xs" c="dimmed">
                Remove
              </Text>
            </Table.Th>
          </Table.Tr>
        </Table.Thead>
        <Table.Tbody>
          {lineItemRows(receipt, edited).map((row) => (
            <LineItemRowCells
              key={itemKeys[row.index] ?? `item-${row.index}`}
              row={row}
              rejections={rejections}
              onCommit={onCommit}
              onRemoveItem={onRemoveItem}
            />
          ))}
        </Table.Tbody>
      </Table>
      {addControl}
    </Stack>
  );
}

export function FieldPanel({
  receipt,
  warnings,
  edited,
  rejections,
  onCommit,
  onAddItem,
  onRemoveItem,
  itemKeys,
}: PanelProps) {
  return (
    <Stack gap="md">
      <Title order={2} size="h5">
        What the model read
      </Title>

      {warnings.length > 0 ? (
        <Alert color="yellow" title="The arithmetic does not add up">
          <Stack gap="xs">
            {warnings.map((warning) => (
              <Text key={warning.check} size="sm">
                {warning.message}
              </Text>
            ))}
            <Text c="dimmed" size="xs">
              The app changed nothing to close the gap. Correct a value below and
              the app runs both checks again.
            </Text>
          </Stack>
        </Alert>
      ) : null}

      <FlatFields
        receipt={receipt}
        warnings={warnings}
        edited={edited}
        rejections={rejections}
        onCommit={onCommit}
      />
      <LineItems
        receipt={receipt}
        edited={edited}
        rejections={rejections}
        onCommit={onCommit}
        onAddItem={onAddItem}
        onRemoveItem={onRemoveItem}
        itemKeys={itemKeys}
      />

      <Text c="dimmed" size="xs">
        Type over any value and press Enter or leave the field to keep it. The app
        checks what you typed against the same rules it checked the model&apos;s
        answer with, and runs both arithmetic checks again. A refused value stays
        out of the receipt and the field keeps what it held. Your corrections live
        in this
        browser tab, so the download is how you keep them.
      </Text>
    </Stack>
  );
}
