import type { ArithmeticWarning } from "./arithmetic";
import type { EditedFields } from "./field-edit";
import type { Receipt } from "./receipt-schema";

/**
 * The session table: where a scanned receipt lives between one reload and the
 * next, and nowhere else.
 *
 * Two browser stores do two jobs here, because they have two lifetimes. The id
 * that says which tab a record belongs to sits in `sessionStorage`, which is per
 * tab and dies with the tab, and that is exactly the lifetime the spec asks of
 * the table. The records themselves sit in IndexedDB, which is per origin and
 * outlives any one tab, so each record carries its session id and a record whose
 * session is gone is simply never listed. The alternative, a database named
 * after the session, leaves a pile of databases no code opens again. This module
 * deliberately sweeps nothing and deletes nothing: removing a visitor's data
 * unasked is the thing this repo does not do.
 *
 * Nothing here throws. A private window, cleared site data or a browser set to
 * block site data can make either store throw on the plainest access, and a
 * rejected promise inside a React effect would blank a panel the visitor is
 * reading. So every call answers with a reported absence instead: `putReceipt`
 * resolves false, `listSessionReceipts` resolves empty, `getReceipt` resolves
 * null, and the app runs with the one receipt on screen the way it did before
 * this slice. The failure is logged once rather than on every call, because a
 * put runs on every accepted edit and a broken store would otherwise fill the
 * console.
 *
 * The store is reached through `globalThis.indexedDB` and `globalThis.sessionStorage`
 * rather than through a captured reference, which is the seam the suite uses: the
 * tests stub both globals and drive the whole module in a Node environment with
 * no browser. The open database is cached against the factory that opened it, so
 * a test that stubs a second factory gets a second database rather than the one
 * an earlier test left behind.
 */

/** The IndexedDB database this app owns. One per origin. */
const DATABASE_NAME = "ai-receipt-scanner";

const DATABASE_VERSION = 1;

/** The object store holding one record per scanned receipt, keyed by `id`. */
const STORE_NAME = "receipts";

/**
 * The index over `sessionId`.
 *
 * Listing a session's receipts is a keyed read against this index rather than a
 * scan of every record the origin holds filtered in JavaScript, so a visitor who
 * opens a second tab pays nothing for the first tab's records.
 */
const SESSION_INDEX = "sessionId";

/** Where the tab's own session id sits in `sessionStorage`. */
const SESSION_STORAGE_KEY = "ai-receipt-scanner.session-id";

/**
 * One stored receipt: the download envelope plus the three facts the table needs.
 *
 * `receipt`, `warnings` and `edited` are the same three keys `receiptToJson`
 * already writes, so a reopened receipt needs no reconstruction and the batch
 * export reads the same shape as the single one. `id`, `sessionId` and `savedAt`
 * sit beside the receipt and never inside it, for the same reason the line item
 * row keys never reach it: an id is a fact about this browser, not about the
 * receipt, and `receiptSchema` governs what sits under `receipt`.
 *
 * Exactly six keys, and no image. The app stores no upload, so a reopened
 * receipt has fields and no picture.
 */
export type StoredReceipt = {
  /** Generated by the browser, never by the model. The object store's key. */
  id: string;
  /** Which tab session wrote this record. The index reads this. */
  sessionId: string;
  /** Milliseconds since the epoch, which is what orders the list newest first. */
  savedAt: number;
  receipt: Receipt;
  warnings: ArithmeticWarning[];
  edited: string[];
};

/**
 * A random id for a record or a session.
 *
 * `crypto.randomUUID` needs a secure context, which the deployed app and
 * `localhost` both are, so the fallback exists for the one case where a browser
 * hands back no `crypto` at all. The id only has to be unique inside one
 * browser's own store, so a timestamp beside two random runs is enough there.
 */
function randomId(): string {
  try {
    const source = globalThis.crypto;
    if (source && typeof source.randomUUID === "function") {
      return source.randomUUID();
    }
  } catch {
    /* falls through to the arithmetic below */
  }

  const noise = `${Math.random().toString(36).slice(2)}${Math.random().toString(36).slice(2)}`;
  return `${Date.now().toString(36)}-${noise}`;
}

/** Logged once per page, because a put runs on every accepted edit. */
let reported = false;

function reportOnce(what: string, cause?: unknown): void {
  if (reported) {
    return;
  }
  reported = true;
  console.warn(
    `session store: ${what}. The receipt on screen keeps working and the session list stays empty.`,
    cause === undefined ? "" : cause,
  );
}

/**
 * The tab's `sessionStorage`, or null when the browser will not hand it over.
 *
 * Reading the property itself throws in a browser set to block site data, which
 * is why the guard wraps the read rather than only the `getItem` that follows.
 */
function sessionStorageOrNull(): Storage | null {
  try {
    return globalThis.sessionStorage ?? null;
  } catch {
    return null;
  }
}

function readStoredSessionId(): string | null {
  try {
    const stored = sessionStorageOrNull()?.getItem(SESSION_STORAGE_KEY);
    return stored && stored.length > 0 ? stored : null;
  } catch {
    return null;
  }
}

function writeSessionId(id: string): boolean {
  try {
    const storage = sessionStorageOrNull();
    if (!storage) {
      return false;
    }
    storage.setItem(SESSION_STORAGE_KEY, id);
    return true;
  } catch {
    return false;
  }
}

/**
 * Holds the session id for a page whose `sessionStorage` refused the write.
 *
 * The lifetime drops from the tab to the page, so a reload loses that session's
 * records rather than reopening them. A browser that blocks site data blocks
 * IndexedDB too, so in practice there is nothing to reopen, and the app reports
 * an empty table either way.
 */
let pageSessionId: string | null = null;

/**
 * The tab's session id, created on the first call and reused on every later one.
 *
 * `sessionStorage` is what makes it survive a reload and die with the tab, so a
 * second visitor in a second tab sees none of the first tab's receipts.
 */
export function tabSessionId(): string {
  const stored = readStoredSessionId();
  if (stored) {
    return stored;
  }

  const created = randomId();
  if (writeSessionId(created)) {
    return created;
  }

  reportOnce("sessionStorage would not keep a session id, so this page's receipts end with it");
  pageSessionId ??= created;
  return pageSessionId;
}

/**
 * A fresh record for a receipt the app just extracted.
 *
 * `warnings` and `edited` are copied rather than held, because the workspace
 * rebuilds both on every edit and a record that shared the array would change
 * under the table. `edited` arrives as the readonly list the edit module hands
 * around and leaves as a plain array, which is what `structuredClone` stores.
 */
export function newStoredReceipt(
  receipt: Receipt,
  warnings: ArithmeticWarning[],
  edited: EditedFields = [],
): StoredReceipt {
  return {
    id: randomId(),
    sessionId: tabSessionId(),
    savedAt: Date.now(),
    receipt,
    warnings: [...warnings],
    edited: [...edited],
  };
}

/** The browser's IndexedDB, or null when there is none to reach. */
function indexedDbOrNull(): IDBFactory | null {
  try {
    const factory: IDBFactory | undefined = globalThis.indexedDB;
    return factory ?? null;
  } catch {
    return null;
  }
}

/**
 * The open database, cached against the factory that opened it.
 *
 * A failed open clears the cache before it resolves, so a store that was
 * unavailable on the first receipt is tried again on the second rather than
 * being written off for the life of the page.
 */
let open: { factory: IDBFactory; database: Promise<IDBDatabase | null> } | null = null;

function openDatabase(): Promise<IDBDatabase | null> {
  const factory = indexedDbOrNull();
  if (!factory) {
    reportOnce("this browser offers no IndexedDB");
    return Promise.resolve(null);
  }

  if (open?.factory === factory) {
    return open.database;
  }

  const database = new Promise<IDBDatabase | null>((resolve) => {
    const give = (value: IDBDatabase | null) => {
      if (value === null && open?.factory === factory) {
        open = null;
      }
      resolve(value);
    };

    let request: IDBOpenDBRequest;
    try {
      request = factory.open(DATABASE_NAME, DATABASE_VERSION);
    } catch (error) {
      reportOnce("IndexedDB refused to open", error);
      give(null);
      return;
    }

    /*
     * The one schema step: a store keyed by the record's own id, and the index
     * the session list reads. Both are created only when they are missing, so a
     * later version bump that adds something else leaves these alone.
     */
    request.onupgradeneeded = () => {
      const upgrading = request.result;
      const store = upgrading.objectStoreNames.contains(STORE_NAME)
        ? request.transaction?.objectStore(STORE_NAME)
        : upgrading.createObjectStore(STORE_NAME, { keyPath: "id" });

      if (store && !store.indexNames.contains(SESSION_INDEX)) {
        store.createIndex(SESSION_INDEX, "sessionId", { unique: false });
      }
    };

    request.onsuccess = () => give(request.result);
    request.onerror = () => {
      reportOnce("IndexedDB would not open", request.error);
      give(null);
    };
    request.onblocked = () => {
      reportOnce("another tab holds an older version of the database open", request.error);
      give(null);
    };
  });

  open = { factory, database };
  return database;
}

/**
 * Runs one request inside one transaction and answers with `fallback` on any
 * failure.
 *
 * Every public call below goes through here, which is what makes a broken store
 * a reported absence rather than a rejected promise inside a render.
 */
async function run<T>(
  mode: IDBTransactionMode,
  describe: string,
  fallback: T,
  work: (store: IDBObjectStore) => IDBRequest | null,
  read: (request: IDBRequest) => T,
): Promise<T> {
  const database = await openDatabase();
  if (!database) {
    return fallback;
  }

  return new Promise<T>((resolve) => {
    let request: IDBRequest | null = null;

    try {
      const transaction = database.transaction(STORE_NAME, mode);

      transaction.onerror = () => {
        reportOnce(describe, transaction.error);
        resolve(fallback);
      };
      transaction.onabort = () => {
        reportOnce(describe, transaction.error);
        resolve(fallback);
      };
      transaction.oncomplete = () => {
        resolve(request === null ? fallback : read(request));
      };

      request = work(transaction.objectStore(STORE_NAME));
    } catch (error) {
      reportOnce(describe, error);
      resolve(fallback);
    }
  });
}

/**
 * Writes a record, replacing any record already under that id.
 *
 * The workspace puts the record again on every accepted edit rather than only on
 * extraction, so the stored copy is true at all times rather than at scan time.
 * A false answer means the table did not take the write; the receipt on screen
 * is the authority either way.
 */
export function putReceipt(record: StoredReceipt): Promise<boolean> {
  return run(
    "readwrite",
    "IndexedDB would not store a receipt",
    false,
    (store) => store.put(record),
    () => true,
  );
}

/**
 * This session's records, newest first.
 *
 * The read is keyed on the session index, so another tab's records are never
 * fetched and never filtered out. The sort runs over what the index returned
 * because IndexedDB orders an index read by its key, which is the session id
 * here and says nothing about time.
 */
export function listSessionReceipts(): Promise<StoredReceipt[]> {
  const sessionId = tabSessionId();

  return run<StoredReceipt[]>(
    "readonly",
    "IndexedDB would not list this session's receipts",
    [],
    (store) => store.index(SESSION_INDEX).getAll(sessionId),
    (request) => {
      const rows = (request.result ?? []) as StoredReceipt[];
      return [...rows].sort((a, b) => b.savedAt - a.savedAt);
    },
  );
}

/** One record by its id, or null when it is absent or the store is unavailable. */
export function getReceipt(id: string): Promise<StoredReceipt | null> {
  return run<StoredReceipt | null>(
    "readonly",
    "IndexedDB would not read a receipt",
    null,
    (store) => store.get(id),
    (request) => (request.result as StoredReceipt | undefined) ?? null,
  );
}
